/*
 * This program is free software; you can redistribute it and/or modify it under the
 * terms of the GNU Lesser General Public License, version 2.1 as published by the Free Software
 * Foundation.
 *
 * You should have received a copy of the GNU Lesser General Public License along with this
 * program; if not, you can obtain a copy at http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html
 * or from the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * Copyright (c) 2001 - 2009 Object Refinery Ltd, Pentaho Corporation and Contributors..  All rights reserved.
 */

package org.pentaho.reporting.engine.classic.core;

import org.pentaho.reporting.engine.classic.core.filter.types.bands.CrosstabGroupType;
import org.pentaho.reporting.engine.classic.core.style.ElementStyleKeys;

/**
 * A crosstab group represents the page, row, column and detail sections of a cube. The other axises are handled as
 * regular relational groups.
 * <p/>
 * The group's header and footer can be used to print page-axis header and footer sections for the crosstab, but they
 * will not be used as bands for the tab-header and -footers. The crosstabs column and row headers are autogenerated and
 * part of the group-body.
 *
 * @author Thomas Morgner
 */
public class CrosstabGroup extends Group
{
  public CrosstabGroup()
  {
    setElementType(new CrosstabGroupType());
    getStyle().setBooleanStyleProperty(ElementStyleKeys.USE_MIN_CHUNKWIDTH, true);
  }

  protected GroupBody createDefaultBody()
  {
    return new CrosstabRowGroupBody();
  }

  public boolean isGroupChange(final DataRow dataRow)
  {
    // always false. We do only return if one of the parent groups claims that there is a group change.
    return false;
  }

  public void setBody(final GroupBody body)
  {
    if (body instanceof CrosstabRowGroupBody == false &&
        body instanceof CrosstabOtherGroupBody == false)
    {
      throw new IllegalArgumentException();
    }
    super.setBody(body);
  }
}
