/*
 * This program is free software; you can redistribute it and/or modify it under the
 * terms of the GNU Lesser General Public License, version 2.1 as published by the Free Software
 * Foundation.
 *
 * You should have received a copy of the GNU Lesser General Public License along with this
 * program; if not, you can obtain a copy at http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html
 * or from the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * Copyright (c) 2001 - 2009 Object Refinery Ltd, Pentaho Corporation and Contributors..  All rights reserved.
 */

package org.pentaho.reporting.engine.classic.testcases.samplereport;

public class OrderReportData extends JdbcTableModel {

	private static final long serialVersionUID = 1L;

	protected String getQuery() {
		return "SELECT CUSTOMERS.CUSTOMERNUMBER AS CUSTOMERS_CUSTOMERNUMBER, CUSTOMERS.CUSTOMERNAME AS CUSTOMERS_CUSTOMERNAME, CUSTOMERS.CONTACTLASTNAME AS CUSTOMERS_CONTACTLASTNAME, CUSTOMERS.CONTACTFIRSTNAME AS CUSTOMERS_CONTACTFIRSTNAME, CUSTOMERS.PHONE AS CUSTOMERS_PHONE, CUSTOMERS.ADDRESSLINE1 AS CUSTOMERS_ADDRESSLINE1, CUSTOMERS.CITY AS CUSTOMERS_CITY, CUSTOMERS.STATE AS CUSTOMERS_STATE, CUSTOMERS.POSTALCODE AS CUSTOMERS_POSTALCODE, CUSTOMER_W_TER.CUSTOMERNUMBER AS CUSTOMER_W_TER_CUSTOMERNUMBER, CUSTOMER_W_TER.TERRITORY AS CUSTOMER_W_TER_TERRITORY, ORDERS.ORDERNUMBER AS ORDERS_ORDERNUMBER, ORDERS.ORDERDATE AS ORDERS_ORDERDATE, ORDERS.REQUIREDDATE AS ORDERS_REQUIREDDATE, ORDERS.SHIPPEDDATE AS ORDERS_SHIPPEDDATE, ORDERS.STATUS AS ORDERS_STATUS, ORDERS.COMMENTS AS ORDERS_COMMENTS, ORDERS.CUSTOMERNUMBER AS ORDERS_CUSTOMERNUMBER, ORDERFACT.ORDERNUMBER AS ORDERFACT_ORDERNUMBER, ORDERFACT.PRODUCTCODE AS ORDERFACT_PRODUCTCODE, ORDERFACT.QUANTITYORDERED AS ORDERFACT_QUANTITYORDERED, ORDERFACT.PRICEEACH AS ORDERFACT_PRICEEACH, ORDERFACT.ORDERLINENUMBER AS ORDERFACT_ORDERLINENUMBER, ORDERFACT.TOTALPRICE AS ORDERFACT_TOTALPRICE, ORDERFACT.ORDERDATE AS ORDERFACT_ORDERDATE, ORDERFACT.REQUIREDDATE AS ORDERFACT_REQUIREDDATE, ORDERFACT.SHIPPEDDATE AS ORDERFACT_SHIPPEDDATE, ORDERFACT.STATUS AS ORDERFACT_STATUS, ORDERFACT.COMMENTS AS ORDERFACT_COMMENTS, ORDERFACT.CUSTOMERNUMBER AS ORDERFACT_CUSTOMERNUMBER, ORDERFACT.TIME_ID AS ORDERFACT_TIME_ID, ORDERFACT.QTR_ID AS ORDERFACT_QTR_ID, ORDERFACT.MONTH_ID AS ORDERFACT_MONTH_ID, ORDERFACT.YEAR_ID AS ORDERFACT_YEAR_ID, PAYMENTS.CUSTOMERNUMBER AS PAYMENTS_CUSTOMERNUMBER, PAYMENTS.CHECKNUMBER AS PAYMENTS_CHECKNUMBER, PAYMENTS.PAYMENTDATE AS PAYMENTS_PAYMENTDATE, PAYMENTS.AMOUNT AS PAYMENTS_AMOUNT, CUSTOMERS.ADDRESSLINE2 AS CUSTOMERS_ADDRESSLINE2, CUSTOMERS.COUNTRY AS CUSTOMERS_COUNTRY FROM PUBLIC.CUSTOMERS CUSTOMERS, PUBLIC.CUSTOMER_W_TER CUSTOMER_W_TER, PUBLIC.ORDERS ORDERS, PUBLIC.ORDERFACT ORDERFACT, PUBLIC.PAYMENTS PAYMENTS WHERE CUSTOMERS.CUSTOMERNUMBER = CUSTOMER_W_TIER.CUSTOMERNUMBER AND ORDERS.CUSTOMERNUMBER = CUSTOMER.CUSTOMERNUMBER AND PAYMENTS.CUSTOMERNUMBER = ORDERS.CUSTOMERNUMBER AND ORDERS.ORDERNUMBER = ORDERFACT.ORDERNUMBER"; //$NON-NLS-1$
	}
}
